### ISSUE TITLE
[feat]: View/Add Peers in UI

### ISSUE THREAD

**Issue by RpiController** [Start9Labs/cln-startos#140]
### Prerequisites

- [X] I have searched for existing issues that already suggest this feature.

### Describe the Feature Request

Please add functionality to view and add peers, similar to the existing options on AlbyHub.
![image](https://github.com/user-attachments/assets/9cd9b63f-fa75-4c8a-91d4-2e4d51f8bc0c)

### Describe the Use Case

Useful to know and manage peer group. It helps connectivity issues.

### Describe Preferred Solution

Make the Peers icon a menu to manage peers.
![image](https://github.com/user-attachments/assets/d4290e3c-9a45-4166-9fc6-9f788bc203cc)

**Comment by Dominion5254** [comment]
The UI in cln-startos is a submodule of [this](https://github.com/ElementsProject/cln-application) repo; If this is a feature you would like to see added, the cln-application repo would be the appropriate place to open an issue.

However, it is worth noting the UI provided by [Ride the Lightning](https://marketplace.start9.com/ride-the-lightning) already allows for similar functionality managing peers.

**Comment by RpiController** [comment]
Makes sense. Yeah, I just realized why the CLN built-in UI is so clunky and basic... because everyone uses RTL. Why re-invent the wheel?
