### ISSUE TITLE
[bug]: sync healthcheck sometimes shows error message while starting

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/cln-startos#37]
<img width="522" alt="Screen Shot 2022-04-04 at 5 34 29 PM" src="https://user-images.githubusercontent.com/7445670/161642973-bacb451a-7ec1-4e7c-b7be-e7d6e131a549.png">

**Comment by ProofOfKeags** [comment]
good chance that this tries to run before c-lightning actually has created the socket.
