### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/cln-startos#38]
C-Lightning reported crashing with the following:

`The service c-lightning has crashed with the following exit code: 134 Details: Serving RPC on 0.0.0.0:8080 Generating a RSA private key ............+++++ ...................+++++ writing new private key to './certs/key.tmp.pem' ----- writing RSA key bitcoin-cli -rpcconnect=btc-rpc-proxy.embassy -rpcport=8332 -rpcuser=... -rpcpassword=... getblockhash 682356 exited 1 (after 99 other errors) 'error: server returned HTTP error 503 '; we have been retrying command for --bitcoin-retry-timeout=60 seconds; bitcoind setup or our --bitcoin-* configs broken? The Bitcoin backend died. lightningd: FATAL SIGNAL 6 (version v0.10.2-modded) 0x559487feb7 send_backtrace common/daemon.c:33 0x559487ff57 crashdump common/daemon.c:46 0x7fb4419a6b ??? ???:0 0x7fb4419af4 ??? ???:0 Log dumped in crash.log.20220419001924 Lost connection to the RPC socket. Lost connection to the RPC socket. Lost connection to the RPC socket. Lost connection to the RPC socket. Lost connection to the RPC socket. Lost connection to the RPC socket.Lost connection to the RPC socket. Lost connection to the RPC socket. `

**Comment by BitcoinMechanic** [comment]
Spark then followed up by reporting a crash too.

**Comment by BitcoinMechanic** [comment]
I guess we should. I also had LND, electrs and BTCPS (configured to use CL) - none of them crashed.

**Comment by chrisguida** [comment]
@ProofOfKeags @dr-bonez @MattDHill should we prevent CL from crashing in this situation? Could be somewhat complicated to implement, but doable

**Comment by ProofOfKeags** [comment]
> @ProofOfKeags @dr-bonez @MattDHill should we prevent CL from crashing in this situation? Could be somewhat complicated to implement, but doable

I don't think we should be doing our own work to prevent this. I would be satisfied with us putting in a request to the CLN team that they are resilient to transient non-responsiveness from Bitcoin Core. I think it is a feature they would implement (eventually) and the maintenance burden of keeping this code around isn't worth it. After all, if Bitcoin Core truly isn't responding in a persistent way, that would be a good reason for CLN to crash.

**Comment by chrisguida** [comment]
Would be fixed by #55
