### ISSUE TITLE
[feat] Add Proxy as a Bitcoin Option in Config

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/cln-startos#39]
Currently only Core is available.  LND allows Proxy, CL should as well

**Comment by chrisguida** [comment]
This is definitely already implemented... where are you seeing this?

**Comment by chrisguida** [comment]
Ah yeah, looks like we left it out on the current prod version. Anyway it's added back here: https://github.com/Start9Labs/c-lightning-wrapper/commit/986a621e87e8b5ed357aec0d9c7fbdda278f0887

Closing
