### ISSUE TITLE
[bug]: CLN REST RPC requests result in 503 Service Unavailable HTTP error code

### ISSUE THREAD

**Issue by gStart9** [Start9Labs/cln-startos#73]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5

### Browser

Firefox

### Browser Version

108

### Current Behavior

When the c-lightning REST API is enabled in CLN's Config, 
![image](https://user-images.githubusercontent.com/106188942/209597699-a46dd03a-70ad-4ca7-96a4-0d10a72c901e.png)

And one goes to view CLN's Interfaces page,
![image](https://user-images.githubusercontent.com/106188942/209597712-ee6856fc-848a-4375-86d7-49ad40383ec8.png)

We should be able to get some information from the REST api, yet curling the /v1/getinfo endpoint that should be available at that URL results in a 503 error:
```
$ curl -sk https://lskixqnpsc2cmj34tnm6mnesk5x3z65bp2dnv4jeelw3zl2q3y66qzid.local/v1/getinfo
503 Service Unavailable
```

It seems as though this is because 9735 and 8080 are the only ports exposed by the Dockerfile:
https://github.com/Start9Labs/c-lightning-wrapper/blob/v0.12.0.1/Dockerfile#L241

If you `netstat -tap` or `ss -tap` inside the container you can see that a node process is listening on port 3001 (api) and 4001 (docs) - but only using ipv6.

So it seems we're just not forwarding the .local from embassy's reverse proxy to the container's port 3001 listener.  We may also need to do something in the CLN package about it not listening on ipv4 0.0.0.0:3001 if the embassy reverse proxy can't do ipv4 to ipv6 forwarding.

Additionally, I noticed I also get a 503 error when querying the json-rpc endpoint (under CLN's Interfaces page).  Not sure if this is related or even an actualy problem, because I"m not sure what endpoint I should be able to hit and if it requires a special json query in the body, but its URL also seems to not work.

### Expected Behavior

Expect curls to api endpoints to result in http 200's and return information.

### Steps to Reproduce

Enable C-Lightning's Plugins CLN Rest API under Config.
Get the REST API URL from the Interfaces page
curl it as depicted above:
curl -svk https://clnrestrpcaddress.local

### Anything else?

This might be related to https://github.com/Start9Labs/c-lightning-wrapper/issues/51 but I'm not sure.

**Comment by chrisguida** [comment]
@gStart9 please verify that this is fixed now

**Comment by gStart9** [comment]
Doesn't seem like it (I am now on the latest from prod published yesterday (22.11.1~2)).
```
$ curl -svk https://myreallysuperlong.local/v1/get_info
*   Trying 10.0.100.152:443...
* Connected to myreallysuperlong.local (10.0.100.152) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=myreallysuperlong.local; O=Start9; OU=Embassy
*  start date: Feb 19 17:53:53 2023 GMT
*  expire date: Mar 22 17:53:53 2024 GMT
*  issuer: CN=Embassy Local Intermediate CA; O=Start9; OU=Embassy
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
> GET / HTTP/1.1
> Host: myreallysuperlong.local
> User-Agent: curl/7.74.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< Content-Length: 23
< Date: Fri, 24 Feb 2023 01:42:29 GMT
< 
* Connection #0 to host myreallysuperlong.local left intact
503 Service Unavailable
```

I really don't understand how this is working given that nothing is listening inside the container on any ipv4 address on port 3001:
```
root@c-lightning:~# netstat -peanut
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      0          144045779  83/c-lightning-http 
tcp        0      0 127.0.0.11:37509        0.0.0.0:*               LISTEN      0          144048222  -                   
tcp        0      0 0.0.0.0:9735            0.0.0.0:*               LISTEN      0          144050231  129/lightning_conne 
tcp        0      0 172.18.0.7:40990        172.18.0.1:9050         ESTABLISHED 0          144057404  129/lightning_conne 
**tcp6       0      0 :::3001                 :::*                    LISTEN      0          144048294  93/node             **
tcp6       0      0 :::4001                 :::*                    LISTEN      0          144048295  93/node             
udp        0      0 127.0.0.1:56766         127.0.0.11:53           ESTABLISHED 0          144341569  14877/bitcoin-cli   
udp        0      0 127.0.0.11:40551        0.0.0.0:*                           0          144048221  -                   
udp        0      0 127.0.0.1:34827         127.0.0.11:53           ESTABLISHED 0          144340491  14835/bitcoin-cli
```

And yet I get some kind of response when I curl it inside the container (although not the one I was expecting):
```
root@c-lightning:~# curl -svk https://127.0.0.1:3001/v1/get_info -H "Host: myreallysuperlong.local"
*   Trying 127.0.0.1:3001...
* Connected to 127.0.0.1 (127.0.0.1) port 3001 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=myreallysuperlong.local; O=Start9; OU=Embassy
*  start date: Feb 19 17:53:53 2023 GMT
*  expire date: Mar 22 17:53:53 2024 GMT
*  issuer: CN=Embassy Local Intermediate CA; O=Start9; OU=Embassy
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
> GET /v1/get_info HTTP/1.1
> Host: myreallysuperlong.local
> User-Agent: curl/7.74.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization, filePath, macaroon, encodingtype
< Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE, OPTIONS
< Content-Security-Policy: default-src 'none'
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 150
< Date: Fri, 24 Feb 2023 02:06:52 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /v1/get_info</pre>
</body>
</html>
* Connection #0 to host 127.0.0.1 left intact
```

What is the intended use of this URL?  Maybe it goes into a special app that is using some construct that I am not with this simple test.

I don't remember what even prompted me to create this issue.  Any idea, @shyfire-131

**Comment by chrisguida** [comment]
Is there a specific downstream service that is running into this 503? Otherwise I don't see the point of this issue.

**Comment by chrisguida** [comment]
Closing since this issue's purpose was forgotten. Feel free to reopen if someone remembers.

**Comment by shyfire-131** [comment]
IIRC this issue was preventing using CLN with a wallet app like Zeus. However with the updated CLN in the beta marketplace Zeus is now working, so I think closing it is the right move.

**Comment by chrisguida** [comment]
@shyfire-131 thanks for getting back!
